# Generated by Django 4.2.5 on 2023-10-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menu_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bookingDate',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='no_of_guest',
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default='Manish', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_date',
            field=models.DateField(default='2023-10-13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_slot',
            field=models.SmallIntegerField(default=10),
        ),
    ]
