# Generated by Django 4.2.5 on 2023-10-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_booking_bookingdate_remove_booking_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='reservation_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='bookingDate',
            field=models.DateTimeField(default='2023-10-13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Manish', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='no_of_guest',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
