# Generated by Django 4.2.5 on 2023-10-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_booking_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bookingDate',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='no_of_guest',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='reservation_slot',
        ),
    ]
