# Generated by Django 4.2.5 on 2023-10-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_booking_bookingdate_remove_booking_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookingDate',
            field=models.DateTimeField(default='2023-10-13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Manish', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='no_of_guest',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_slot',
            field=models.SmallIntegerField(default=10),
        ),
    ]
