# Generated by Django 4.2.5 on 2023-10-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_booking_bookingdate_booking_name_booking_no_of_guest_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='bookingModel',
        ),
    ]
