# Generated by Django 4.2.5 on 2023-10-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_rename_booking_bookingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('no_of_guest', models.IntegerField()),
                ('bookingDate', models.DateTimeField()),
                ('reservation_slot', models.SmallIntegerField(default=10)),
            ],
        ),
        migrations.DeleteModel(
            name='bookingModel',
        ),
    ]
