# Generated by Django 4.2.5 on 2023-10-13 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_booking_model_delete_bookingmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_model',
            old_name='bookingDate',
            new_name='reservation_date',
        ),
    ]
