# Generated by Django 4.2.5 on 2023-10-13 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_rename_bookingdate_booking_model_reservation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_model',
            old_name='name',
            new_name='first_name',
        ),
    ]
